project_name: tfnotify
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: tfnotify
    ldflags: 
      - -s -w
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: 'darwin'
      linux: 'linux'
      windows: 'windows'
      386: '386'
      amd64: 'amd64'
    format_overrides:
      - goos: 'windows'
        format: 'zip'
release:
  prerelease: auto
